version: '3.8'

services:
    db:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: fil_rouge
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            timeout: 3s
            retries: 10
        ports:
            - '3306:3306'
        volumes:
            - db-data:/var/lib/mysql
            - ./sql-scripts:/docker-entrypoint-initdb.d

    app:
        build: .
        container_name: springboot-app
        ports:
            - '8080:8080'
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fil_rouge
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
        depends_on:
            db:
                condition: service_healthy

volumes:
    db-data:
